spring:
  config:
    import:
      - classpath:/config/database-config.yml
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect:
          dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: info
